image: codefreshplugins/cfstep-image-promotion
categories:
  - Security
version: 0.1.0
description: "Step to promote Docker image in Codefresh pipeline"
keywords:
  - codefresh
  - registry
sources:
  - https://github.com/codefresh-contrib/cfstep-image-promotion
maintainers:
  - name: Dustin Van Buskirk
    email: dustinb@codefresh.io
icon: https://cdn.jsdelivr.net/gh/codefresh-io/steps/graduated/push/icon-2.svg
envs:
  - name: CODEFRESH_API_URL
    description: Codefresh API URL
  - name: CF_API_KEY 
    description: Codefresh API Key
  - name: CF_BUILD_INITIATOR 
    description: Codefresh build initiator (defaulted to pipeline executor)
  - name: CODEFRESH_USERNAME 
    description: Codefresh Username if different from CF_BUILD_INITIATOR
  - name: IMAGE 
    description: Source Docker image tag
  - name: PROMOTE_IMAGE 
    description: Docker image name to Promote (if different from IMAGE) 
  - name: PROMOTE_TAG 
    description: Docker image tag to Promote (if different from TAG) 
  - name: REGISTRY
    description: Docker registry name as known in Codefresh
  - name: TAG 
    description: Source Docker image name
